// Generated by CoffeeScript 1.4.0
var Dirtle, fs,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

fs = require('fs');

Dirtle = (function() {

  module.exports = Dirtle;

  function Dirtle(path, interval) {
    this.path = path;
    this.interval = interval;
    this.doBackup = __bind(this.doBackup, this);

    this.stringify = __bind(this.stringify, this);

    this.dumpSync = __bind(this.dumpSync, this);

    this.dump = __bind(this.dump, this);

    this.setupSync = __bind(this.setupSync, this);

    this.interval || (this.interval = 470);
    this.setupSync();
    this.doBackup();
    process.on('exit', this.dumpSync);
    this.db;
  }

  Dirtle.prototype.setupSync = function() {
    return this.db = JSON.parse(fs.readFileSync(this.path, 'utf8'));
  };

  Dirtle.prototype.dump = function(cb) {
    return fs.writeFile(this.path, this.stringify(), 'utf8', cb);
  };

  Dirtle.prototype.dumpSync = function() {
    return fs.writeFileSync(this.path, this.stringify(), 'utf8');
  };

  Dirtle.prototype.stringify = function() {
    return JSON.stringify(this.db);
  };

  Dirtle.prototype.doBackup = function() {
    var _this = this;
    return setInterval((function() {
      return _this.dump(function() {});
    }), this.interval);
  };

  return Dirtle;

})();
